### ISSUE TITLE
Split ZTE F601 page into subpages

### ISSUE THREAD

**Issue by nanomad** [hack-gpon/hack-gpon.github.io#122]
We currently have one big page for ZTE's F601, it would be nicer to align it to the Nokia ONTs where we have one page for hardware revision since some of the info is different (HW version, SW version, chipset, cpu, ...)

**Comment by simonebortolin** [comment]
I would also add that the fact that there are currently no commands, etc., should they come up, it will become unmanageable.

**Comment by nanomad** [comment]
@simonebortolin can we close this? I think the latest F601 page is good enough
