### ISSUE TITLE
Halny HL-GSFP: missing too much setup config

### ISSUE THREAD

**Issue by BittorB** [hack-gpon/hack-gpon.github.io#179]
Hello

I provide some info from halny module
Openwrt 14.07
UART 38400 8N1
IP 192.168.77.154 mask 255.255.255.252
No web interface
SSH via por 22666
To change password you need to enter via UART and then enter failsafe mode to change password

**Comment by AreYouLoco** [comment]
@BittorB I wanted to post info you find out here as well :-)

**Comment by BittorB** [comment]
still im researching and dumping my all SFP gpon modules to make a GIT backup

**Comment by BittorB** [comment]
root password hash is this. 
root:$1$8CRVpRmx$JF6lIkgRj94q3KdfMHlLS1:18298:0:99999:7:::

Partition layout is totally diferent to zisa op151s

**Comment by stich86** [comment]
Can you post more infos? I think this is the only SFP that lacks a lot of information :)

**Comment by BittorB** [comment]
Partition layout

dev:    size   erasesize  name
mtd0: 00040000 00010000 "uboot"
mtd1: 00020000 00010000 "uboot_env"
mtd2: 003d0000 00010000 "image0"
mtd3: 003d0000 00010000 "linux"
mtd4: 002a87aa 00010000 "rootfs"
mtd5: 000a0000 00010000 "rootfs_data"

**Comment by collerok** [comment]
in my case the password hash is 

> root:$1$hbfFkJkQ$5TjpP2bvm3Mu2JPvN86.M0:18158:0:99999:7:::
but is yet unknown (

**Comment by vuducdong** [comment]
@BittorB 

this sfp have webpage is http://192.168.77.154/cgi-bin/halny_settings

and login with:

user = halnysettings
password = HaLnYxyz 

- this password is different for each SFP, where x, y, z are:
#	x is 2nd byte of MAC address
#	y is 4th byte of MAC address
#	z is 5th byte of MAC address

**Comment by AreYouLoco** [comment]
Did someone figure out default SNMP community?
