### ISSUE TITLE
Technicolor AFM0002

### ISSUE THREAD

**Issue by mihait** [hack-gpon/hack-gpon.github.io#201]
Hello !
I have two Technicolor AFM0002TIM software V1_7_8_210412 and V1_7_8_210928 and some commands from the wiki are not working at all on both sticks.

/etc/scripts/flash set HW_HWVER MYHWVERSION
/etc/scripts/flash set GPON_ONU_MODEL DFP-34X-XXX
/etc/scripts/flash set OMCI_OLT_MODE 2
/etc/scripts/flash set OMCI_FAKE_OK 1

All the above commands are failing. Is the wiki wrong or something must be done before issuing them on the stick ?

**Comment by nanomad** [comment]
The patch is actually wrong, thanks for bringing that up
