### ISSUE TITLE
technicolor-afm0002 - serial SFP pinout

### ISSUE THREAD

**Issue by y-martin** [hack-gpon/hack-gpon.github.io#22]
Hello

Do you know if it's possible to have serial console via SFP connector on this SFP ?

Regards

**Comment by nanomad** [comment]
We never tried IIRC. I do have a logic analyzer at hand so I will give it a go

**Comment by nanomad** [comment]
Unfortuntaly i did probe all the relevant pins and saw nothing of use. Feel free to-reopen the issue if you spot something
