### ISSUE TITLE
Is this a community that discriminates against LGBT? Probably yes

### ISSUE THREAD

**Issue by MorrisVal** [hack-gpon/hack-gpon.github.io#232]
Still no response to my request, in the meantime I wrote a Tweet

**Comment by simonebortolin** [comment]
there is already an open issue on this topic #231

**Comment by MorrisVal** [comment]
Clearly your motivation to close this is that you feel disgust towards LGBT people

**Comment by simonebortolin** [comment]
please use the main issue #231

**Comment by simonebortolin** [comment]
Despite the OP's unfriendly ways, his request was approved and implemented as #234 #237.
