### ISSUE TITLE
FS GPON stick upload speed is below the subscription speed.

### ISSUE THREAD

**Issue by KyunKyun87** [hack-gpon/hack-gpon.github.io#241]
is there any command to reset the GPON laser? it is because every time the GPON stick reboot and the upload speed is very slow (is like below 100mbps). However when I try to remove and connect back the SC cable, the upload speed back to full speed. Any idea what cause the issue?

**Comment by simonebortolin** [comment]
What firmware? Original or modded?

**Comment by KyunKyun87** [comment]
> modded

The original firmware, 6BA1896SPLQA42

**Comment by simonebortolin** [comment]
We need @ErnyTech

**Comment by ErnyTech** [comment]
I need more data about the used OLT, router and configuration on FS.com

**Comment by KyunKyun87** [comment]
All I know the OLT once for side is provide by FIberhome. On the FS ONU mostly is default setting from the GitHub page.

**Comment by simonebortolin** [comment]
this ONT performs poorly in upload with huawei OLTs. a known fact.
