### ISSUE TITLE
CIG Password Generator

### ISSUE THREAD

**Issue by dirdi** [hack-gpon/hack-gpon.github.io#246]
Hi there, is there something known about the algorithm to generate CIG passwords (e.g. used by https://hack-gpon.org/ont-cig-g-97cp/#enable-password)?

I generated a bunch of passwords and did some quick basic cryptanalysis on them:
* Passwords consists of upper and lower case letters, as well as digits.
* However, `o`, `O`, `I`, `B`, `0`, `1`, and `8` are not used.
* Relative frequencies for each character (based on 10k generated passwords):
![image](https://github.com/hack-gpon/hack-gpon.github.io/assets/7914030/92fc71e6-1b45-4005-8eee-d62248a95b99)

**Comment by nanomad** [comment]
> Hi there, is there something known about the algorithm to generate CIG passwords (e.g. used by https://hack-gpon.org/ont-cig-g-97cp/#enable-password)?
>

The algorithm has been fully reverse engineered, we are choosing not to disclose it to minimize the chance of CIG changing it.

**Comment by simonebortolin** [comment]
If there are any needs related to this tool please contact us at the institutional email simonebortolin at hack-gpon.org
