### ISSUE TITLE
technicolor-afm0002 - firmware

### ISSUE THREAD

**Issue by y-martin** [hack-gpon/hack-gpon.github.io#25]
Hello @nanomad  @simonebortolin  @Andreag00 

I'm looking for a recent firmware like V1_7_8_210928 for this module. Do you known where I can find it ?
I see in your doc that your sfp as a more recent version. Can you dump kernel & rootfs ?

Regards

**Comment by simonebortolin** [comment]
Hi, no need to edit the message to tag us (and send us a second notification), the notification had already reached us, we are investigating to see if any of us have that firmware.

**Comment by simonebortolin** [comment]
In any case, try asking in the telegram group, sharing dumps on the web is not a good idea.

**Comment by nanomad** [comment]
Closed, as this is not a file-sharing site :)
