### ISSUE TITLE
ONT FS - VLAN Tagging

### ISSUE THREAD

**Issue by toomuchio** [hack-gpon/hack-gpon.github.io#251]
Hi,

I've got the stick correctly authenticating and I can see the expected VLAN in the table, but if I tag the VLAN on my router the same as I do with the ODI stick it doesn't seem to pass traffic down.

Is there an issue with the FS ONT and VLAN mapping or a setting that needs to be changed to make it work?

**Comment by toomuchio** [comment]
I see, so it looks like the FS ONT strips the VLAN ID and sets it to 0... Which is odd.

Is there a way to force these things to operate in a transparent mode like ODI?

**Comment by toomuchio** [comment]
Further info, so vlan tagging starts at 1, which Microtik unfortunately uses as it's default vlan.

A firmware modification would be needed to start the vlan mapping further along, likely. Perhaps the person that modified omcid could provide some insight here

**Comment by ErnyTech** [comment]
I don't see how this could be a problem. The SFP works as expected using the VLAN Table provided by the OLT 
through ME 171, the problem with using VLAN 1 is related to your Mikrotik configuration

**Comment by toomuchio** [comment]
Hi Erny,

You're right this is a problem with my Tik cfg, I can make it work with vlan 1 but because of the way the tik switching asic is designed and their hard fixed use of VLAN ID 1 with bridges, if you do that.

You loose hardware offloading and all traffic goes via the CPU.

The ODI sticks just do a native/transparent trunk mode, so if the OLT provides VLAN 60 in my case, I tag VLAN 60. There's no issue, but if I use the Lantiq stick they do a remap.

So in my case VLAN 60 is mapped to 1, then VLAN 65 is mapped to 2, and since VLAN 1 is a 'reserved' vlan it creates this issue on the tiks.

So I'm wondering is there a way to make the Lantiq map transparently like ODI or can we find the integer and change it's initial value to something other than 1. So the mapping would start at like 20 or something. 

Looks like it might be a function in omcid bin again, but I'm not sure.

**Comment by ErnyTech** [comment]
> You loose hardware offloading and all traffic goes via the CPU.

I don't know which Mikrotik I use but if you don't have L3 offload support the traffic goes to the CPU anyway as it has to route from the internet to your LAN.
Removing the SFP from the hw offload bridge does not change any performance in this case.

> So I'm wondering is there a way to make the Lantiq map transparently like ODI or can we find the integer and change it's initial value to something other than 1. So the mapping would start at like 20 or something.

I will never implement such a thing, the transparent mode violates the OMCI GPON standard by not respecting the VLAN Table of the ME 171 and I have no intention of doing so due to problems on the user's router.

**Comment by toomuchio** [comment]
It does have L3 offload support, but that goes away the second you try and use VLAN 1 in a bridge since vlan1 is used internally by the tik, by not forcing it you just see all packets coming from the stick stripped of the vlan id setting it to 0 by the tik.

Not wanting transparent is fair enough but is there some way to offset the vlan mapping so 1 isn't used for the first vlan mapped, that would solve the issue. This is a tik issue absolutely, but a lot of other switch vendors do use occasionally use vlan1 for internal use as well it's very uncommon to see anything using vlan1.

**Comment by nanomad** [comment]
Closing as non-issue
