### ISSUE TITLE
CIG (Q-010G-Q) password generator not accessible

### ISSUE THREAD

**Issue by systemcrash** [hack-gpon/hack-gpon.github.io#252]
Tried to generate a password for my NOKIA ONT Q-010G-Q, which has a serial beginning: ALCL then 4 (hex) bytes, as opposed to GPON:

`ALCLXXXXXXXX`

But that's a problem for:

https://cigpassword.hack-gpon.org/?serial=GPONabc12345&username=ONTUSER

Something that can/must be fixed?

**Comment by simonebortolin** [comment]
Can you show a screenshot of the probem?

The link work

**Comment by systemcrash** [comment]
> Can you show a screenshot of the probem?
> 
> The link work



> has a serial `ALCLXXXXXXXX`

```
GPON S/N in format GPONabc12345
Please provide a valid GPON S/N. 
```

**Comment by nanomad** [comment]
Seems to be working just fine. 
![image](https://github.com/hack-gpon/hack-gpon.github.io/assets/1129926/2eef283c-08a3-445f-a1ee-64781e060de2)

You can join the telegram group then message me and we will check why yours is not working. The link is at the top of the website

**Comment by systemcrash** [comment]
The error message is entirely misleading, and conflates the lower-case problem (a-z) with the requirement that it starts with GPON. 

Is it difficult to `strlower` or similar in the code? Or does the code function for various devices and one cannot make this assumption?

**Comment by systemcrash** [comment]
And/Or write a less confusing error message, like:
`If your device serial is ASDFABCDEF10 - please enter ASDFabcdef10`

**Comment by systemcrash** [comment]
Lower-case for the HEX part seems to work. 👍 
Thanks for the help.

**Comment by nanomad** [comment]
> Lower-case for the HEX part seems to work. 👍 Thanks for the help.

Feel free to try the API now. It should give the same output with any case you put

**Comment by systemcrash** [comment]
"should"
```
GPON S/N in format GPONabc12345
Please provide a valid GPON S/N. 
```

**Comment by nanomad** [comment]
My fault :) Missed a manual deploy step. I'll update the issue once it's done

**Comment by nanomad** [comment]
@systemcrash backend and front-end both updated. Let me know if we can mark this as resolved

![Uploading image.png…]()

**Comment by systemcrash** [comment]
Seems good, although the success/failure messages are a bit terse.

`GPON S/N in format GPONabc12345`

**Comment by simonebortolin** [comment]
please, suggest an alterative text

**Comment by nanomad** [comment]
@simonebortolin here's what I would do

- [ ] Clear output fields on keyup of input field. Otherwise i keep forgetting that I need to press the blue button :)
- [ ] Can we hide the "green" message if the validation succeeds?
- [ ] As an error message, I would use: Invalid GPON S/N format. Please make sure it is in the format GPONabc12345

**Comment by simonebortolin** [comment]
@nanomad 
point 1 is acceptable, but there is also a need to make the same change on several other forms and/or delete the submit button itself and do it as in the eeprom form with vue.

for point 2 and 3 ummh makes sense, let's wait for @systemcrash's opinion

**Comment by systemcrash** [comment]
How about: `Unrecognized GPON S/N format. S/N are typically of the form XXXXDEADBEEF, where XXXX is commonly GPON or ALCL`.
