### ISSUE TITLE
Racist and xenophobic hate

### ISSUE THREAD

**Issue by DavidL43** [hack-gpon/hack-gpon.github.io#256]
Members of this community hate disabled people and people of color, I was personally insulted in private by one of the administrators

**Comment by nanomad** [comment]
We don't take those accusations lightly, feel free to share the relevant screenshots here so we can take appropriate actions

**Comment by DavidL43** [comment]
> We don't take those accusations lightly, feel free to share the relevant screenshots here so we can take appropriate actions

I cannot share them due to my disability which prevents me from doing so

**Comment by DavidL43** [comment]
@simonebortolin insulted and threatened me, he must be withdrawn from the board

**Comment by nanomad** [comment]
> @simonebortolin insulted and threatened me, he must be withdrawn from the board

There's no such thing as a "board". Also, without proof it's an unsubstantiated accusation made by an account  created 17 minutes ago. I'm closing this as a poor trolling attempt

**Comment by simonebortolin** [comment]
Nonsense
