### ISSUE TITLE
LEOX GPON STICK LXT-010S-H

### ISSUE THREAD

**Issue by qatar2030** [hack-gpon/hack-gpon.github.io#266]
From https://github.com/hack-gpon/hack-gpon.github.io/pull/44#issuecomment-1685081743

> @qatar2030  i have LEOX GPON STICK LXT-010S-H and it was working great with mikrotik rb5009 and when i change mode from flash set LAN_SDS_MODE 1 to flash set LAN_SDS_MODE 8 the sfp stop working any help please

> @stich86 Which version of RouterOS and Firmware do you have?
> 
> The support was added by 7.3 or later. Make sure that firmware (under System/RouterBOARD) is update otherwise 2.5Gbit// doesn't work

> @qatar2030 > Which version of RouterOS and Firmware do you have?
> > The support was added by 7.3 or later. Make sure that firmware (under System/RouterBOARD) is update otherwise 2.5Gbit// doesn't work
> 
> My SFP firmware version is V3.3.4L4rc1 (Fix 2.5GbE HiSGMII) and my Mikrotik version 7.11 ![Screenshot 2023-08-20 094654](https://user-images.githubusercontent.com/89544455/261836115-9fecaac2-76f9-4c41-b798-32007ec55f9c.png) ![Screenshot 2023-08-20 094711](https://user-images.githubusercontent.com/89544455/261836118-88c32349-cef6-465c-a6e6-0efc1d1158f1.png) and someone taled me that I have to have media convertor 2.5G instead 1G to change sfp mode to fiber ![Screenshot 2023-08-20 095302](https://user-images.githubusercontent.com/89544455/261836243-e918cb17-04cd-4bc8-bb4b-1d6a5eec2dc4.png)

**Comment by qatar2030** [comment]
https://github.com/hack-gpon/hack-gpon.github.io/pull/44#issuecomment-1685203812

**Comment by simonebortolin** [comment]
From https://github.com/hack-gpon/hack-gpon.github.io/pull/44#issuecomment-1685081743

> @qatar2030  i have LEOX GPON STICK LXT-010S-H and it was working great with mikrotik rb5009 and when i change mode from flash set LAN_SDS_MODE 1 to flash set LAN_SDS_MODE 8 the sfp stop working any help please



> @stich86 Which version of RouterOS and Firmware do you have?
> 
> The support was added by 7.3 or later. Make sure that firmware (under System/RouterBOARD) is update otherwise 2.5Gbit// doesn't work



> @qatar2030 > Which version of RouterOS and Firmware do you have?
> > The support was added by 7.3 or later. Make sure that firmware (under System/RouterBOARD) is update otherwise 2.5Gbit// doesn't work
> 
> My SFP firmware version is V3.3.4L4rc1 (Fix 2.5GbE HiSGMII) and my Mikrotik version 7.11 ![Screenshot 2023-08-20 094654](https://user-images.githubusercontent.com/89544455/261836115-9fecaac2-76f9-4c41-b798-32007ec55f9c.png) ![Screenshot 2023-08-20 094711](https://user-images.githubusercontent.com/89544455/261836118-88c32349-cef6-465c-a6e6-0efc1d1158f1.png) and someone taled me that I have to have media convertor 2.5G instead 1G to change sfp mode to fiber ![Screenshot 2023-08-20 095302](https://user-images.githubusercontent.com/89544455/261836243-e918cb17-04cd-4bc8-bb4b-1d6a5eec2dc4.png)

**Comment by simonebortolin** [comment]
I'm told by the director that everything is okay
