### ISSUE TITLE
10G ONU

### ISSUE THREAD

**Issue by graphine27** [hack-gpon/hack-gpon.github.io#27]
Hi, do you have any info about 10G devices?
I found this https://service-provider.zyxel.com/global/en/products/fiber-oltsonts/xgs-pon/unbundled/pm7000-01
It is used in combination with AX7501-B0 but I wonder if it can work in any device with SFP cage or is simply a transceiver and no GPON processing is done on the SFP device itslef.

**Comment by nanomad** [comment]
Unfortunately it is just a Transceiver, so it only converts the optical signal to the relevant data signals on the SFP+ lines. The MAC side is done inside the CPE (e.g. AX7501-B0)

**Comment by nanomad** [comment]
@graphine27 Just to add, an example of an XGS-PON ONU with MAC is the CIG XG-99S (https://www.cigtech.com/wired-access/)

**Comment by graphine27** [comment]
Thanks, also found https://ecin.ca/xgs-pon-sfp-stick-module-xgspon-ont-w-t-mac-function-mounted-on-sfp-package/
