### ISSUE TITLE
Zyxel PM3000-D20B works with 57810S chipset in 2.5G LAN mode 

### ISSUE THREAD

**Issue by sodaws** [hack-gpon/hack-gpon.github.io#278]
Hi, as described [here](https://github.com/xvzf/zyxel-gpon-sfp/issues/10#issuecomment-1722289076), this ONT SFP works with the 57810S NICs.

The page for this module states otherwise. The infos for incompatibility were added in d016d17 and 97a603f (#103). What was the source for that info? Does this maybe only count for certain firmware versions of the Zyxel? Only talking about LAN speed, not speed to the OLT of course.

**Comment by stich86** [comment]
> Hi, as described [here](https://github.com/xvzf/zyxel-gpon-sfp/issues/10#issuecomment-1722289076), this ONT SFP works with the 57810S NICs.
> 
> 
> 
> The page for this module states otherwise. The infos for incompatibility were added in d016d17 and 97a603f (#103). What was the source for that info? Does this maybe only count for certain firmware versions of the Zyxel? Only talking about LAN speed, not speed to the OLT of course.

So the problem is with MOD_ABS PIN (6) that's not grounded

At this point it's better to modify the network card (more easily). Same issue is present with HiSense stick that doesn't ground PIN 6

**Comment by sodaws** [comment]
Yes, but I'm also asking why does the wiki page specifically states that 2.5G LAN does not work?

**Comment by nanomad** [comment]
> Yes, but I'm also asking why does the wiki page specifically states that 2.5G LAN does not work?

The wording could be better I think, feel free to submit a PR clarifying this (It's due to the PIN config as explained by @stich86 )
