### ISSUE TITLE
Sercomm FG1000B.11 // Glasfaser Modem 2 Config?

### ISSUE THREAD

**Issue by ChrSch84** [hack-gpon/hack-gpon.github.io#279]
Hello iam new here so please have mercy.

i got a Glasfaser Modem 2 and whant to use it as my ONT. I managed to get on the ONT with telnet (not permanent only via browser console) shown on the wiki.

But every thing else is a show stopper to me. I dont understand the wiki :)

What i want to do is swap my  "HG8010Hv6" with the "Glasfaser Modem2". 

I got my PW and SN from my HG8010Hv6. But how do i put them on the "NEW ONT".

i know i should work with telnet because there is no GUI. -> Only for Germany LWL Telekom Users.

Thank you

**Comment by ChrSch84** [comment]
I could not find out the Problem every time is try the new Ont i get State: 03 Seriel Number.

is there no one who can help me? Thank you

**Comment by nanomad** [comment]
You need to figure out the kind of authentication and checks done by your OLT. Feel free to join the telegram group and we can discuss this there

**Comment by reinierjh** [comment]
Did you ever find the problem?
I can change the serial number but only with the gponctl command.
Connection works. But after a reboot the original serial number is active. even after changing the gpon_sn file.

**Comment by ChrSch84** [comment]
No did not find the Problem... 

But my ISP changed my ONT to the "same Modell" so i know now that i only need the PW &SN but it still does not work.
