### ISSUE TITLE
Question ZTE F6005

### ISSUE THREAD

**Issue by Gruni22** [hack-gpon/hack-gpon.github.io#285]
Hi, thanks for your great work!!!
I have a question regarding ZTE F6005.
I cannot get serial connection. Is it disabled by default?
Is there any chance to change parameters?
Do I need to flash to access it?
The description is misleading.

**Comment by Gruni22** [comment]
Thank you for the fast response!
Then I must have bought crap 👎

**Comment by abonforti** [comment]
> > I cannot get serial connection. Is it disabled by default?
> 
> in firmware distributed in Italy yes, in others we do not know
> 
> > Is there any chance to change parameters?
> 
> Only if you change the firmware
> 
> > Do I need to flash to access it?
> 
> only if you cannot load firmware from gui
> 
> > The description is misleading.
> 
> you can change it

Hi, I have the same problem and as mentioned, I can't establish a serial connection. How is it possible to flash the firmware (and in case which one) given the fact that the web interface is not having (apparently) this possibility?
