### ISSUE TITLE
Huawei EchoLife HG8110H-20

### ISSUE THREAD

**Issue by rytisp** [hack-gpon/hack-gpon.github.io#291]
Has anyone tried to access web interface or telnet of Huawei EchoLife HG8110H-20?
.100.1 doesn’t work.

**Comment by simonebortolin** [comment]
is it a custom version for some ISP? it will most likely be disabled

**Comment by rytisp** [comment]
> is it a custom version for some ISP? it will most likely be disabled

Probably custom. BT UK.

**Comment by simonebortolin** [comment]
Bt wants armoured olts inaccessible to users. Useless to work with. Use authentication via gpon serial numeber
