### ISSUE TITLE
No Info or working link for : ont-ECIN-EN-XGSFPP-OMAC-v1.md

### ISSUE THREAD

**Issue by Akira1947** [hack-gpon/hack-gpon.github.io#292]
https://github.com/hack-gpon/hack-gpon.github.io/blob/main/_ont_xgs/ont-ECIN-EN-XGSFPP-OMAC-v1.md

**Comment by simonebortolin** [comment]
this is correct, this link redirect to other ONT that are very very similar, if new or different things come up we will remove the link and make the page, for now v1 is an alias of the FS.

ECINv2 is MaxLinear and will most likely have a page
