### ISSUE TITLE
[Request] Huawei HN8010Ts clone guide

### ISSUE THREAD

**Issue by ChaosYoda** [hack-gpon/hack-gpon.github.io#315]
Can you please add a guide, and possibly explain what details need to be copied and transferred from the Huawei HN8010Ts to one of the SFP+ modules so that you can just swap it out in place?

**Comment by simonebortolin** [comment]
No guidance will be made as the parameters to be changed change from OLT to OLT.
Generally the rule of thumb says:
- OLT Nokia: hardware version, software version, equipment id + GPON S/N or GPON PLOAM Passowrd or GPON LOID
- Huawei OLT with third-party licenses for ONT: GPON S/N or GPON PLOAM Passowrd or GPON LOID
- Huawei OLT without third-party licenses for ONT: Custom Huawei MIB + Vendor HWTC + GPON S/N or GPON PLOAM Passowrd or GPON LOID
- OLT ZTE: GPON S/N or GPON PLOAM Passowrd or GPON LOID
- ....
So there are too many cases and it is impossible to make a generic guide, as well as difficult to update.

if you need ideas for what to configure ask us.
