### ISSUE TITLE
Backup goi config prior to re-flash

### ISSUE THREAD

**Issue by benbgg** [hack-gpon/hack-gpon.github.io#324]
It says here: https://hack-gpon.org/ont-huawei-ma5671a-carlito/
"Info Be careful, backup goi_config from uboot before changing the firmware."
I'm trying to re-flash a GPON-ONU-34-20BI - with Huawei firmware
Can I do this once booted? If I have to do it from within U-Boot, that means I need serial access, right?

Sorry for so many questions, I hope I'm not the only one having to ask them!

**Comment by simonebortolin** [comment]
https://hack-gpon.org/ont-huawei-ma5671a/#backup-of-all-partition
