### ISSUE TITLE
ZTE F6005 V3.0.10P3N2

### ISSUE THREAD

**Issue by davidebeatrici** [hack-gpon/hack-gpon.github.io#348]
Firmware: `V3.0.10P3N2`

Logging in with `admin`/`admin` shows a very limited menu:

![ZTE_F6005_1](https://github.com/hack-gpon/hack-gpon.github.io/assets/5897523/b65ad170-b199-4d2c-b8f1-5b7b8e7bb25e)
![ZTE_F6005_2](https://github.com/hack-gpon/hack-gpon.github.io/assets/5897523/de161478-bf44-4f74-bc30-f0bb26dcbf67)

**Comment by davidebeatrici** [comment]
![](https://github.com/hack-gpon/hack-gpon.github.io/assets/5897523/e320f048-d42f-48fd-92d4-3467a3f5d861)

**Comment by xTheEl988** [comment]
Ciao, potresti dirmi come posso configurare l’id servizio “AAAXXXXX” nella versione corrente. Grazie mille

**Comment by davidebeatrici** [comment]
Effettuare un dump del firmware e sbloccarlo o modificare l'impostazione manualmente potrebbe essere l'unica via...
